# Generated by Django 5.0.6 on 2024-05-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='is_3v3',
            field=models.BooleanField(default=True),
        ),
    ]
