# Generated by Django 5.0.6 on 2024-05-15 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_rules_is_3v3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rules',
            new_name='Rule',
        ),
    ]
