# Generated by Django 4.0.4 on 2024-05-12 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_player_ame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='ame',
        ),
    ]
